### ISSUE TITLE
No need for Certifiers group

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#103]
Anyone registered can certify maps and layers

**Comment by waybarrios** [comment]
I fixed for layer by https://github.com/cga-harvard/worldmap/commit/9a25f783a0435d1f09864d8d933f5b90c68a8fcd

**Comment by waybarrios** [comment]
Done for maps by https://github.com/cga-harvard/worldmap/commit/9434c9747190bc0a8532c57dfd850604cdd4e9d8

**Comment by capooti** [comment]
Let's fix permissions before we close this. This way we can test to certify objects with different priviledges

**Comment by capooti** [comment]
This is closed.
