### ISSUE TITLE
Permissions for migrated layers have not been migrated

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#111]
Public layer in legacy WorldMap should be public in new version too.

Looking at one public layer in WorldMap like this one:

http://worldmap.harvard.edu/data/geonode:cambridge_districts_2zs

![screenshot 2017-10-05 13 39 03](https://user-images.githubusercontent.com/148380/31241653-94ca6b3e-a9d2-11e7-95a3-ff50d6cb933d.png)

In new version the layer is not public and permissions are not consistent with the old version:

http://128.31.22.103/layers/geonode:cambridge_districts_2zs

![screenshot 2017-10-05 13 40 27](https://user-images.githubusercontent.com/148380/31241711-c41037b6-a9d2-11e7-8084-bd1ce70e747c.png)

**Comment by waybarrios** [comment]
I fixed it by https://github.com/piensa/worldmap-migration/commit/207ef8e3888d5d2ec131aecda8414c811ea9447f
It only remains to transfer the repository to this organization

**Comment by capooti** [comment]
was the migration applied to the staging instance? Because I just checked some of my private layers and permissions seem still unmigrated

**Comment by waybarrios** [comment]
So, can you check it using this url: http://128.31.22.103:8000/? Otherwise, I need to change DATABASE_URL  on uwsgi file.

**Comment by capooti** [comment]
I am looking at one layer for which these are the current permissions in WorldMap:

<img width="342" alt="screenshot 2017-10-11 15 22 46" src="https://user-images.githubusercontent.com/148380/31461629-1b863850-ae98-11e7-948e-ca73dcdb01d4.png">

here is now how it looks in new version:

<img width="342" alt="screenshot 2017-10-11 15 22 46" src="https://user-images.githubusercontent.com/148380/31461676-33ce4efc-ae98-11e7-8e19-5e22452c1065.png">

There are several wrong things in my opinion:

* the layer should not be seen by anyone but only by registered users. In order to get this I think we should have a "registered" users group. We should have a post registration signals which append each registered user to that group
* "who can download" it should be consistent with "who can view it" (and it is not)
* "who can change metadata", "who can edit data", "who can edit styles" should be the same users/groups of "who can edit this".
* "who can manage it" should be the same users/groups as in "Who can manage and edit this?". In this case it is correct

We may consider to have in legacy worldmap two implicit groups: "registered users" and "haravard users". They must be created in the database (and they are not), so I think you should start from there.

**Comment by waybarrios** [comment]
As you mentioned: _“the layer should not be seen by anyone but only by registered users”_ I have a trouble right now. For example, If I’m not authenticated, I cannot see all layers in the map, fulfilling the above criteria. So, you can see  all layers in the map, you must log in. What do you think @capooti @ingenieroariel  ?

**Comment by capooti** [comment]
If all layers in that map are visible only to registered users, then the above behaviour is correct in my opinion. I would expect that the map owner would set the map visibility to registered users as well, though it is on the owner to do such a thing.

**Comment by capooti** [comment]
@waybarrios @ingenieroariel this is how I would translate legacy permissions to new system:
https://docs.google.com/spreadsheets/d/1IiNYEJRu8_Ix2kWdwhWyzTXZvDm3CsRHYzPBT2UIqk0/edit?usp=sharing

**Comment by waybarrios** [comment]
<img width="510" alt="captura de pantalla 2017-10-13 a la s 1 35 34 p m" src="https://user-images.githubusercontent.com/6794828/31560871-a1f0f298-b01b-11e7-84cd-9e61cceb6624.png">
<img width="505" alt="captura de pantalla 2017-10-13 a la s 1 35 22 p m" src="https://user-images.githubusercontent.com/6794828/31560872-a211cb30-b01b-11e7-94bd-a86ea1d22c79.png">
<img width="516" alt="captura de pantalla 2017-10-13 a la s 1 35 07 p m" src="https://user-images.githubusercontent.com/6794828/31560873-a2303c5a-b01b-11e7-913f-4b3238aa79a9.png">

**Comment by waybarrios** [comment]
Is this what you expect? @capooti

**Comment by waybarrios** [comment]
By the way, we must modify the registry for a new user to be associated with the group of `registered users`.

**Comment by capooti** [comment]
It is correct, but the checkbox for "anyone" in view and download sections must be checked as well.

**Comment by capooti** [comment]
Yes, that can be easily done with a post_save signal raised by people.profile in our project (no need to fork GeoNode)

**Comment by waybarrios** [comment]
if the checkbox for "anyone" is checked, it means no authenticated user can see the layer, so that confuses me a little bit @capooti

**Comment by capooti** [comment]
Anyone is anyone, includes also registered users :)

**Comment by capooti** [comment]
So @waybarrios what is the status of this?
If I open one layer I still don't see migrated permissions: http://128.31.22.103/layers/geonode:bra_planning_districts_2015_zip_pnq

**Comment by capooti** [comment]
Another thing I noticed.
When I create/upload new layers I can see corresponding geofence data rules in security > geofence data rules.
I don't see any rules for the migrated layers. I am wondering if this can cause problems (though migrated layers seems correctly displaying)

/cc @ingenieroariel 

<img width="919" alt="screenshot 2017-10-20 12 08 50" src="https://user-images.githubusercontent.com/148380/31830892-95f498cc-b58f-11e7-9ac3-960eb6e915fe.png">

**Comment by waybarrios** [comment]
@capooti One thing we never forget is to assign new users to `Registered users` group when they signed up

**Comment by capooti** [comment]
I will create a ticket with that
