### ISSUE TITLE
TopicCategory is not correctly migrated

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#122]
TopicCategory for resources is not correctly migrated.

Check for example this layer:

http://worldmap.harvard.edu/data/geonode:high_speed_rail_lines_2016_40k
Transportation

http://128.31.22.103/layers/geonode:high_speed_rail_lines_2016_40k
no category

This could be caused by the fact that TopicCategory entries in WorldMap are slightly different than in GeoNode.

**Comment by capooti** [comment]
Old WM:

<img width="560" alt="screenshot 2017-10-20 15 00 03" src="https://user-images.githubusercontent.com/148380/31837592-684f4d50-b5a7-11e7-8534-62ea62665e34.png">

New WM:

<img width="644" alt="screenshot 2017-10-20 14 59 55" src="https://user-images.githubusercontent.com/148380/31837601-6dba51e0-b5a7-11e7-8b12-11e7ca5a83be.png">

**Comment by capooti** [comment]
Correspondence (/cc @bglewis )

Old WorldMap -> New WorldMap

biota -> Ecology & Biota
boundaries -> Boundaries
climatologyMeteorologyAtmosphere -> Climate & Weather
economy -> Economic Activities & Employment
elevation -> Elevation
environment -> Environmental Resources, Conservation
farming -> Farming & Agriculture
geoscientificInformation --> ?
health -> Health & Human Ecology
imageryBaseMapsEarthCover -> Imagery & Base Maps
inlandWaters -> Rivers, Streams, Lakes
intelligenceMilitary -> Military Bases & Activities
location -> Place Locations
oceans -> Oceans
planningCadastre -> Planning & Cadastral Data
society -> Society & Demographics
structure -> Structures
transportation -> Transportation
utilitiesCommunication -> Utilities & Infrastructure

Remove boundaries (there are two instance) in new database.

**Comment by capooti** [comment]
@waybarrios I see the correct categories now in Admin. Does the migration script correctly handle them for each layer?

**Comment by waybarrios** [comment]
I got all info from Old database @capooti

**Comment by capooti** [comment]
great, thanks!
