### ISSUE TITLE
Category icons are not displayed

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#126]
@ingenieroariel maybe Lennin could help here?
Locally for me it is working

Locally

<img width="682" alt="screenshot 2017-10-20 15 44 05" src="https://user-images.githubusercontent.com/148380/31839089-92e1204c-b5ad-11e7-8e07-67ebbd3a8e3f.png">

Staging

<img width="497" alt="screenshot 2017-10-20 15 44 25" src="https://user-images.githubusercontent.com/148380/31839094-9734606e-b5ad-11e7-9112-3428e655b405.png">

**Comment by waybarrios** [comment]
I loaded `initial_data.json` and only appers the following. 
Can you show me your initial_data @capooti ? 
![image](https://user-images.githubusercontent.com/6794828/31948403-74265e82-b89c-11e7-8369-750e78c759e1.png)

**Comment by waybarrios** [comment]
![image](https://user-images.githubusercontent.com/6794828/31948538-ce16ed08-b89c-11e7-9e67-0a0dd1385c04.png)

**Comment by capooti** [comment]
Great. If you pull code on the server I can close this. Thanks!

**Comment by waybarrios** [comment]
Done https://github.com/cga-harvard/worldmap/commit/61da819d071d39f062c33199ceea0210917a807b

![image](https://user-images.githubusercontent.com/6794828/31959857-8abc9020-b8bb-11e7-8bd4-72ad9362e3a4.png)
