### ISSUE TITLE
TopicCategory tables lacks  description and description_en

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#127]
This is causing a lot of failures (for example when updating categories).

This is how it should look:

<img width="1390" alt="screenshot 2017-10-20 16 01 35" src="https://user-images.githubusercontent.com/148380/31839638-fb8b5ade-b5af-11e7-9422-24a72a4b68c1.png">

This is how it looks now:

<img width="1391" alt="screenshot 2017-10-20 16 01 43" src="https://user-images.githubusercontent.com/148380/31839649-04c2b21e-b5b0-11e7-9391-9dd1ba5c433b.png">

**Comment by waybarrios** [comment]
Done by https://github.com/cga-harvard/worldmap/commit/61da819d071d39f062c33199ceea0210917a807b

![image](https://user-images.githubusercontent.com/6794828/31959811-5e3105e0-b8bb-11e7-9964-c0b467fe127e.png)

**Comment by capooti** [comment]
It is different from what I see in the staging. Categories seem to have been duplicated there

![screenshot 2017-10-24 14 32 28](https://user-images.githubusercontent.com/148380/31961247-32a0a1ee-b8c8-11e7-841c-3871fd5c6d0b.png)

**Comment by waybarrios** [comment]
I haven't change DATABASE URL yet.
