### ISSUE TITLE
Create a fixture to create the default WorldMap groups

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#132]
<img width="501" alt="screenshot 2017-10-26 11 28 46" src="https://user-images.githubusercontent.com/148380/32063568-85ac14da-ba45-11e7-9b35-05e4220d5bc5.png">

**Comment by waybarrios** [comment]
Done by: https://github.com/cga-harvard/worldmap/commit/01078d035ff0c7659786a3560b8ab814a1d05cd6

**Comment by waybarrios** [comment]
![worldmap1](https://user-images.githubusercontent.com/6794828/32180587-60b29b9a-bd60-11e7-947d-c35cbca581bf.png)

![worldmap2](https://user-images.githubusercontent.com/6794828/32180598-62aefd6c-bd60-11e7-86cf-8af56a0d1a6a.png)
