### ISSUE TITLE
Create updated documentation to install WorldMap from scratch

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#133]

**Comment by kevincote** [comment]
+1. I just tried installing it from scratch in a clean Ubuntu 16.04 64bits VM. Had several librairies and packages missing and incompatibilities. Had to modify pavement.py, requirements.txt to be able to install (lxml, pygdal). I had some errors with the Java VM also (incompatibility with the JDK I think).

**Comment by waybarrios** [comment]
Im on it @capooti

**Comment by capooti** [comment]
@kevincote please wait. Instructions are correct but there are several problems which need to be fixed and which are causing the build to fail. We are working on this.

**Comment by capooti** [comment]
Documentation is now synced with latest developments. Thanks @waybarrios
