### ISSUE TITLE
404 on multiple librairies when loading the map composer

### ISSUE THREAD

**Issue by kevincote** [cga-harvard/worldmap#137]
I've deployed the app following the newest installation documentation. After starting the local server and geoserver, I'm able to get to the worldmap portal. 

When trying to create a map, the GeoExplorer instance does not load. In my console, I'm getting 404 errors for multiple JS files.

![image](https://user-images.githubusercontent.com/31894882/32332388-c3c24020-bfbb-11e7-84bd-4b2ac5aaa2f5.png)

**Comment by capooti** [comment]
This is weird. Which way did you start GeoServer and Django?

**Comment by kevincote** [comment]
As specified in the doc, with `paver start_geoserver` in cga-worldmap folder and `python manage.py runserver 0.0.0.0:8000` in the worldmap folder

**Comment by capooti** [comment]
Did you make any change in settings.py file, or you are just running the code as it is?

**Comment by kevincote** [comment]
I've made no changes at all, just followed procedure. And I don't know if it's worth something but I don't have any `gxp.js` file in both worldmap and cga-worldmap directories. Also, when starting GeoServer, I'm having a very long error about jetty. Small part of the message:

![image](https://user-images.githubusercontent.com/31894882/32333642-c5add5c2-bfbe-11e7-8f73-59b14762c1da.png)

Could this be the source ?

**Comment by capooti** [comment]
Well, with respect to GeoServer and Jetty, that should be the same log as in GeoNode master. I know there are several errors because of monitoring and geofence but it should still work.
Regarding the geoexplorer error later today I will rebuild everything in order to see if I can replicate it. thanks for reporting

**Comment by kevincote** [comment]
Thank you. And FYI, I've been building worldmap using ubuntu 16.04.03 LTS desktop on a VirtualBox VM.

**Comment by capooti** [comment]
@kevincote we updated several things, today. We are now synced with geonode master.
I couldn't reproduce your problem, could you try from scratch and see if it happens again? thanks

**Comment by kevincote** [comment]
@capooti I just tried from scratch on a clean VM and still gets the 404 on the librairies.

**Comment by capooti** [comment]
Oh, maybe you need to build the javascript, I think built version is not part of the repo.
So try to do this (is in README, I will make it more evident):

cd src/geonode-client
ant buildjs

let me know if this helps

**Comment by kevincote** [comment]
@capooti thanks for pointing that. It worked after building the javascript files. I had to build ringo before being able to build the javascript so that should also be added to the docs. 

Talking about the docs, the `Create the PostGIS role and databases` section should be moved because the gits aren't cloned at this moment and therefore the makefile isn't accessible.

Thanks a lot !

**Comment by capooti** [comment]
thanks to you! If you have time to upgrade docs it would be wonderful :)
