### ISSUE TITLE
Include Table XY

### ISSUE THREAD

**Issue by JorgeMartinezG** [cga-harvard/worldmap#14]
-Application to upload CSV and to make table joins
- UI

**Comment by waybarrios** [comment]
Check it out: https://github.com/jj0hns0n/geonode/tree/table-join/geonode/contrib/datatables

**Comment by capooti** [comment]
Hi, I remember you worked on this, what is the current status? Can we close this ticket or we still need to do this task?

**Comment by ingenieroariel** [comment]
It has been added to the repository so this ticket will be able to be closed. We will show a video of it working during the meeting later today but I think it makes sense for you to verify on your end and then close.

**Comment by capooti** [comment]
I cannot find it in this repository?

**Comment by capooti** [comment]
so is it now part of geonode?
https://github.com/cga-harvard/worldmap/commit/fff31f19e67c139e2d13d82b2b78b38518d2f19b

**Comment by waybarrios** [comment]
yest, it is part of geonode. Can this be closed?

**Comment by capooti** [comment]
I will close it when I have the chance to test it. I am waiting for dataverse team feadback
