### ISSUE TITLE
Optimize performance for geoserver

### ISSUE THREAD

**Issue by JorgeMartinezG** [cga-harvard/worldmap#15]
- Split layers into multiple worskspaces in geoserver.
- Test performance time using new approach

**Comment by waybarrios** [comment]
We are caching tiles on our geoserver. In this case, we had to build xml with all settings per layer including `layer_name`, `srs` and styles. For building xml files, we use the following script: https://gist.github.com/waybarrios/56e50b835ddaf8ea613a164ebae22099 
And for uploading in geoserver, we use `GEOSERVER REST SERVICE` as the following:
```
ls *.xml | xargs -I{} sh -c curl -v -u admin:$PWD -XPUT -H “Content-type: text/xml” -d @{}  “http://localhost:8080/geoserver/gwc/rest/layers/{}”
```

It reduces loaded time per layer in worldmap.

**Comment by waybarrios** [comment]
This is one example:
![image](https://cloud.githubusercontent.com/assets/6794828/26696017/976edec8-46d2-11e7-990d-27bf85e4a15d.png)

**Comment by capooti** [comment]
@waybarrios I am not sure if this is clear. WorldMap is already caching layers. But for some weird reasons many layers were not cached.

**Comment by JorgeMartinezG** [comment]
@capooti we are generating the requests to geoserver to cache layers and updating the geonode database fields with the correct gwc url. Maybe some layers were not cached before by geoserver or geonode is using the normal wms request to geoserver.

**Comment by capooti** [comment]
Yes, for some reasons GeoNode did not configure correctly about 10,000 layers.
This is how the layer in GeoServer must look:

<img width="682" alt="screenshot 2017-06-01 16 12 13" src="https://cloud.githubusercontent.com/assets/148380/26698735/2bfcf63a-46e5-11e7-8100-4ee00fa69c4a.png">

about 10,000 layers have the "Enable tile caching for this layer" checkbox unchecked.

**Comment by waybarrios** [comment]
We have 25K cached layers using the method which @JorgeMartinezG said. 
<img width="1513" alt="screen shot 2017-06-01 at 4 09 40 pm" src="https://cloud.githubusercontent.com/assets/6794828/26701015/134c2dfe-46e5-11e7-84e5-dbf291e2d5d0.png">

Bear in mind,  `worldmap.harvard.edu` refers our AWS IP (cheating PC through etc/hosts)

**Comment by waybarrios** [comment]
@capooti We are looking about what is going on, but using rest request is useful. Also for new layers, the cache is automatic
