### ISSUE TITLE
Add to Map button in layer page doesn't work

### ISSUE THREAD

**Issue by blewis** [cga-harvard/worldmap#156]
Returns error
![image](https://user-images.githubusercontent.com/812849/37118209-758071c0-2221-11e8-9d0a-03a84c7eaa7e.png)

**Comment by capooti** [comment]
Hi Ben
1) thickets are here: https://github.com/cga-harvard/geonode/issues
2) there is already a ticket for this: https://github.com/cga-harvard/geonode/issues/267

thanks anyway

**Comment by capooti** [comment]
This is a WorldMap bug which should be easy to fix. It is in the list
