### ISSUE TITLE
Use styles plugin for geoserver

### ISSUE THREAD

**Issue by JorgeMartinezG** [cga-harvard/worldmap#16]

**Comment by waybarrios** [comment]
Now, I installed `SLD SERVICE REST` for our geoserver version. It is working as you can see below.

![image](https://cloud.githubusercontent.com/assets/6794828/26375078/219d58ca-3fcd-11e7-9b80-45f4dfd65dbc.png)

**Comment by capooti** [comment]
great! does it work with the styler tool in GXP?

**Comment by waybarrios** [comment]
@capooti we are in javascript implementation right now!

**Comment by blewis** [comment]
good news!

**Comment by waybarrios** [comment]
So, classify using `SLD_SERVICE REST` is working through GeoServer Plugin. The following is a quantile classification on the `makkah_built_areas_1974_phe` layer and `BUILTUP_` attribute with a custom color ramp and 3 open intervals.

![image](https://cloud.githubusercontent.com/assets/6794828/26471145/3662f02c-4166-11e7-853a-14b80a28c375.png)

Now, @Lenninlasd is working on this implementation on worldmap client.

**Comment by waybarrios** [comment]
This is the reply from sld request. 

```xml
<Rules>
<Rule>
<Title><= 340.0</Title>
<Filter>
<PropertyIsLessThanOrEqualTo>
<Function name="convert">
<PropertyName>BUILTUP_</PropertyName>
<Literal>java.lang.Double</Literal>
</Function>
<Literal>340.0</Literal>
</PropertyIsLessThanOrEqualTo>
</Filter>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#FF0000</CssParameter>
</Fill>
<Stroke/>
</PolygonSymbolizer>
</Rule>
<Rule>
<Title>> 340.0 AND <= 679.0</Title>
<Filter>
<And>
<PropertyIsGreaterThan>
<Function name="convert">
<PropertyName>BUILTUP_</PropertyName>
<Literal>java.lang.Double</Literal>
</Function>
<Literal>340.0</Literal>
</PropertyIsGreaterThan>
<PropertyIsLessThanOrEqualTo>
<Function name="convert">
<PropertyName>BUILTUP_</PropertyName>
<Literal>java.lang.Double</Literal>
</Function>
<Literal>679.0</Literal>
</PropertyIsLessThanOrEqualTo>
</And>
</Filter>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#AA0055</CssParameter>
</Fill>
<Stroke/>
</PolygonSymbolizer>
</Rule>
<Rule>
<Title>> 679.0</Title>
<Filter>
<PropertyIsGreaterThan>
<Function name="convert">
<PropertyName>BUILTUP_</PropertyName>
<Literal>java.lang.Double</Literal>
</Function>
<Literal>679.0</Literal>
</PropertyIsGreaterThan>
</Filter>
<PolygonSymbolizer>
<Fill>
<CssParameter name="fill">#5500AA</CssParameter>
</Fill>
<Stroke/>
</PolygonSymbolizer>
</Rule>
</Rules>
```

**Comment by capooti** [comment]
Nice!
let's wait for good news from @Lenninlasd then :)

**Comment by waybarrios** [comment]
SLD_REST_CLIENT (frontend) is done @Lenninlasd??

**Comment by waybarrios** [comment]
Frontend Done

**Comment by ingenieroariel** [comment]
Wayner,

Can you add screenshots and links to the commit where it was fixed?

-a

**Comment by waybarrios** [comment]
@ingenieroariel it was done in 2 PR ( #22 and #23) You can also see the interface screenshot in #23
