### ISSUE TITLE
Installing ECW plugin in GeoServer 

### ISSUE THREAD

**Issue by waybarrios** [cga-harvard/worldmap#18]
Geoserver must be able to support ECW.

**Comment by capooti** [comment]
@waybarrios this is a deployment issue. Speaking with @ingenieroariel we will deploy GeoServer manually, correct? I can take care of it.

**Comment by waybarrios** [comment]
This issue is done! We installed `libecwj2-3.3` and gdal with ECW plugin. 
![image](https://cloud.githubusercontent.com/assets/6794828/26362245/f52755ea-3fa2-11e7-870c-44217bc5f399.png)

**Comment by waybarrios** [comment]
good @capooti !

**Comment by waybarrios** [comment]
@capooti This was to test the compatibility of the ECW layers with the new geoserver

**Comment by capooti** [comment]
oh I see. Thanks!
