### ISSUE TITLE
Migrating GeoServer to MOC

### ISSUE THREAD

**Issue by waybarrios** [cga-harvard/worldmap#26]
- [x] Install GeoServer with oauth2 plugin for integration with GeoNode 2.6.x
- [x] Copy all stores and workspace in GeoServer
- [x]  Editing config files for GeoNode authentication & permission.
- [x]  Editing datastore xml file for reading from postgis database in production
- [x] Install SLD service plugin to work with GeoServer REST service
- [x] Install ECW plugin to read these kind of layers in MOC Server.
- [x] Caching all layers in `gwc-layers`.

If I missed tasks, please **do not hesitate to add them**

**Comment by waybarrios** [comment]
- Editing config files for GeoNode authentication & permission: 
https://github.com/waybarrios/geoserver_config/commit/a9ffbbd352877940b5579b3d74be1eba293651d1
- Editing datastore xml file for reading from postgis database in production: 
https://github.com/waybarrios/geoserver_config/commit/ad331a246bd1b5ef4cea9f5864bb3581e80d239b
- Tomcat settings for GeoServer: 
https://github.com/waybarrios/geoserver_config/commit/1c614a4704a00d7643672d63b7f6030537af1cf0

**Comment by waybarrios** [comment]
Done!

**Comment by waybarrios** [comment]
Can you verify it and close? @capooti

**Comment by capooti** [comment]
It is great @waybarrios thanks!
