### ISSUE TITLE
Fix the worldmap responsive

### ISSUE THREAD

**Issue by Lenninlasd** [cga-harvard/worldmap#31]
![image](https://user-images.githubusercontent.com/7197750/28880730-8fa06382-776b-11e7-812a-6b3484ad85e1.png)

![image](https://user-images.githubusercontent.com/7197750/28880769-a7c286a2-776b-11e7-904a-4efcbfac1e09.png)

**Comment by waybarrios** [comment]
Almost Done?

**Comment by Lenninlasd** [comment]
Fixed @waybarrios https://github.com/cga-harvard/worldmap/pull/37
