### ISSUE TITLE
Changing map list webpage on Worldmap

### ISSUE THREAD

**Issue by waybarrios** [cga-harvard/worldmap#34]

**Comment by waybarrios** [comment]
DONE 👍 
Check it out @ingenieroariel 

<img width="1280" alt="captura de pantalla 2017-08-03 a la s 3 36 54 p m" src="https://user-images.githubusercontent.com/6794828/28942751-208413f2-7862-11e7-9d46-6afa0a42a329.png">

<img width="1280" alt="captura de pantalla 2017-08-03 a la s 3 38 36 p m" src="https://user-images.githubusercontent.com/6794828/28942768-309ec8a4-7862-11e7-88e0-a8e418f91686.png">

**Comment by capooti** [comment]
thanks. In the screenshot you can observe a typical spam map :)
