### ISSUE TITLE
Create Layer application

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#48]
Create a new contrib application for GeoNode to create layer from scratch (migrating code from current WM).
Enable the new form page in the "Add layers" GXP form.

**Comment by capooti** [comment]
I am starting working from this using geonode master branch here:
https://github.com/capooti/geonode/tree/create-layer-app

@ingenieroariel @Lenninlasd @waybarrios @JorgeMartinezG if you think we should rather stay on 2.6.1 let me know. But working on master offer us the possibilities to send PR with schema changes if needed

**Comment by capooti** [comment]
This is now in GeoNode master and 2.7.x. So we just need to merge GeoNode master to our version to have in in WorldMap.

**Comment by JorgeMartinezG** [comment]
Already included in our current working repo

https://github.com/piensa/geonode/commits/wm-develop

**Comment by capooti** [comment]
great! thanks
