### ISSUE TITLE
Migration Styles per each layer

### ISSUE THREAD

**Issue by waybarrios** [cga-harvard/worldmap#6]
So, There are two tables on new GeoNode version called `layers_layer_styles` and `layers_style`. 
We need to extract each style per each layer, and then insert on each specific table.

**Comment by capooti** [comment]
Maybe updatelayers will populate the table? (just guessing)

**Comment by waybarrios** [comment]
I'll check it out @capooti

**Comment by waybarrios** [comment]
Done by @JorgeMartinezG and myself!
