### ISSUE TITLE
Re-enable the about tool

### ISSUE THREAD

**Issue by Lenninlasd** [cga-harvard/worldmap#74]

**Comment by waybarrios** [comment]
Done by https://github.com/cga-harvard/worldmap/commit/dbfd5964728c4bc3088814f857444a65cfa29f59

**Comment by waybarrios** [comment]
![image](https://user-images.githubusercontent.com/6794828/30346702-44d2404e-97cf-11e7-9f1d-996f4d0a26bf.png)

**Comment by Lenninlasd** [comment]
@capooti I thing this issue can be closed

**Comment by capooti** [comment]
Yes, I have checked, it is working also in my local version. Closing it.
