### ISSUE TITLE
Migrate the certification application

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#75]

**Comment by capooti** [comment]
I see it is in your current fork @ingenieroariel. Does it make sense to have it as a geonode.contrib application? Otherwise let's move it in the WM project (here)

**Comment by waybarrios** [comment]
I migrated into worldmap project: https://github.com/cga-harvard/worldmap/tree/master/worldmap/certification

**Comment by capooti** [comment]
ok thanks. I will close this after testing it in the staging.
