### ISSUE TITLE
Legend icon is huge

### ISSUE THREAD

**Issue by capooti** [cga-harvard/worldmap#79]
<img width="1324" alt="screenshot 2017-09-14 17 45 14" src="https://user-images.githubusercontent.com/148380/30457210-85e68a12-9974-11e7-9794-b1f5cca93bd0.png">

**Comment by Lenninlasd** [comment]
@capooti can you provide me a link to see this issue?

**Comment by capooti** [comment]
It is in my local development version.
I will have a look at the web site but right now is not available.

**Comment by Lenninlasd** [comment]
@capooti  Exist a way to enable/disable the legend icon? I can't visualize it, neither is loaded by the page ( btw the icon load well in my local geoserver)

![image](https://user-images.githubusercontent.com/7197750/30720659-12c75ac8-9eee-11e7-8d6d-b600fab65354.png)

**Comment by capooti** [comment]
Looking at genodode code, the legend url is injected to the template by ResourceBase get_legend, which use links

https://github.com/cga-harvard/cga-worldmap/blob/wm-master/geonode/base/models.py#L968

You should look at the links in the base/links table and see if there is a record named 'Legend' for that layer. If it is not there try saving again the layer and it should be added (I am not sure why it was not added since the beginning)

<img width="973" alt="screenshot 2017-09-22 09 43 08" src="https://user-images.githubusercontent.com/148380/30747238-945a7f52-9f7a-11e7-817e-4d9e5d604b86.png">

**Comment by capooti** [comment]
thanks @Lenninlasd
